# syntax=docker/dockerfile:1-labs
FROM oven/bun:1.3-alpine AS base
WORKDIR /home/bun/app

COPY package.json bun.lock ./
COPY --parents */*/package.json ./

RUN bun install --frozen-lockfile

COPY . .

ARG APP

WORKDIR "/home/bun/app/apps/$APP"


FROM base AS dev-api

EXPOSE 8080/tcp
ENTRYPOINT [ "bun", "dev" ]


FROM base AS dev-web

ARG ENV_FILE
ENV ENV_FILE=$ENV_FILE

ARG ENTRYPOINT_CMD='caddy run --config /etc/caddy/Caddyfile --adapter caddyfile'
ENV ENTRYPOINT_CMD=$ENTRYPOINT_CMD

EXPOSE 8080/tcp
ENTRYPOINT [ "sh", "./scripts/init.sh" ]
