# syntax=docker/dockerfile:1-labs
FROM oven/bun:1.3-alpine
WORKDIR /home/bun/app

COPY package.json bun.lock ./
COPY --parents */*/package.json ./

RUN bun install --frozen-lockfile

COPY . .

ARG WORKSPACE_TARGET

WORKDIR "/home/bun/app/apps/$WORKSPACE_TARGET"

ARG WEB_ENV_FILE
ENV WEB_ENV_FILE=$WEB_ENV_FILE

RUN ./scripts/init.sh

EXPOSE 8080/tcp
ENTRYPOINT [ "bun", "dev" ]
