apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: vex
build:
  artifacts:
    - image: api
      docker:
        dockerfile: Dockerfile
        buildArgs:
          WORKSPACE_TARGET: api
          ENTRYPOINT_CMD: 'bun --cwd apps/api build/main.js'
        cacheFrom:
          - api
    - image: web
      docker:
        dockerfile: Dockerfile
        buildArgs:
          WORKSPACE_TARGET: web
          ENTRYPOINT_CMD: 'bun --cwd apps/web/build index.html'
        cacheFrom:
          - web
  local:
    useDockerCLI: true
deploy:
  helm:
    releases:
      - name: api
        chartPath: apps/api/k8s
        useHelmSecrets: true
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_api}}'
          image.tag: '{{.IMAGE_TAG_api}}@{{.IMAGE_DIGEST_api}}'
      - name: web
        chartPath: apps/web/k8s
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_web}}'
          image.tag: '{{.IMAGE_TAG_web}}@{{.IMAGE_DIGEST_web}}'
portForward:
  - resourceType: service
    resourceName: api
    port: 8080
    localPort: 9000
  - resourceType: service
    resourceName: web
    port: 8080
    localPort: 9001
