apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: vex

build:
  artifacts:
    - image: api
      docker:
        dockerfile: Dockerfile.prod
        target: release-api
        buildArgs:
          APP: api
        cacheFrom:
          - api
      sync:
        manual:
          - src: 'apps/api/**/*.ts'
            strip: apps/api
            dest: '.'
    - image: web
      docker:
        dockerfile: Dockerfile.prod
        target: release-web
        buildArgs:
          APP: web
        cacheFrom:
          - web
      sync:
        manual:
          - src: 'apps/web/**/*.{ts,tsx,html}'
            strip: apps/web
            dest: '.'
          - src: 'apps/api/**/*.ts'
            strip: apps/api
            dest: ../api
  local:
    useDockerCLI: true

deploy:
  helm:
    releases:
      - name: gateway
        repo: https://traefik.github.io/charts
        remoteChart: traefik
        namespace: traefik
        createNamespace: true
        setValues:
          providers:
            kubernetesIngress:
              enabled: false
            kubernetesGateway:
              enabled: true
          gateway:
            listeners:
              web:
                namespacePolicy:
                  from: All
      - name: api
        chartPath: apps/api/k8s
        useHelmSecrets: true
        skipBuildDependencies: true
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_api}}'
          image.tag: '{{.IMAGE_TAG_api}}@{{.IMAGE_DIGEST_api}}'
        dependsOn: ['gateway']
      - name: web
        chartPath: apps/web/k8s
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_web}}'
          image.tag: '{{.IMAGE_TAG_web}}@{{.IMAGE_DIGEST_web}}'
        dependsOn: ['gateway']

portForward:
  - resourceType: service
    resourceName: gateway-traefik
    namespace: traefik
    port: 80
    localPort: 1337

profiles:
  - name: dev
    requiresAllActivations: false
    activation:
      - command: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: Dockerfile.dev
      - op: replace
        path: /build/artifacts/0/docker/target
        value: dev-api
      - op: replace
        path: /build/artifacts/1/docker/dockerfile
        value: Dockerfile.dev
      - op: replace
        path: /build/artifacts/1/docker/target
        value: dev-web
