apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vex-web.fullname" . }}
  labels:
    app.kubernetes.io/component: server
    {{- include "vex-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      {{- include "vex-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: server
        {{- include "vex-web.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.health.enabled }}
            - name: http-health
              containerPort: {{ .Values.health.port }}
              protocol: TCP
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "vex-web.fullname" . }}
          {{- if .Values.health.enabled }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http-health
          livenessProbe:
            httpGet:
              path: /live
              port: http-health
          {{- end }}
    