apiVersion: v1
kind: Service
metadata:
  name: {{ include "vex-web.fullname" . }}
  labels:
    {{- include "vex-web.labels" . | nindent 4 }}
spec:
  # type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  clusterIP: None
  selector:
    {{- include "vex-web.selectorLabels" . | nindent 4 }}
