apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
spec:
  gatewayClassName: traefik
  listeners:
    - name: api
      protocol: HTTP
      port: 80
      hostname: "api.vex.local"
    - name: web
      protocol: HTTP
      port: 80
      hostname: "app.vex.local"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-api-route
spec:
  parentRefs:
    - name: traefik-gateway
  hostnames:
    - "api.vex.local"
  rules:
    - backendRefs:
        - name: api-vex-api
          port: 8080
