apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
  namespace: traefik
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      port: 8000
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
#       {{ if and (eq .protocol  "HTTPS") (not .certificateRefs) }}
#         {{- fail "ERROR: certificateRefs needs to be specified using HTTPS" }}
#       {{- end }}
#       {{ if or .certificateRefs .mode }}
#       tls:
#         {{ with .mode }}
#         mode: {{ . }}
#         {{- end }}
#         {{ with .certificateRefs }}
#         certificateRefs:
#           {{- toYaml . | nindent 10 }}
#         {{- end }}
#       {{- end }}
#     {{- end }}
# {{- end }}



# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: traefik-gateway
#   namespace: traefik
# spec:
#   gatewayClassName: traefik
#   listeners:
#   - name: http
#     protocol: HTTP
#     port: 80

# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: traefik
#   namespace: default
# spec:
#   gatewayClassName: traefik

#   # Only Routes from the same namespace are allowed.
#   listeners:
#     - name: http
#       protocol: HTTP
#       port: 80
#       allowedRoutes:
#         namespaces:
#           from: Same 

#     - name: https
#       protocol: HTTPS
#       port: 443
#       tls:
#         mode: Terminate
#         certificateRefs:
#           - name: secret-tls
#             namespace: default

#       allowedRoutes:
#         namespaces:
#           from: Same

#     - name: tcp
#       protocol: TCP
#       port: 3000
#       allowedRoutes:
#         namespaces:
#           from: Same

#     - name: tls
#       protocol: TLS
#       port: 3443
#       tls:
#         mode: Terminate
#         certificateRefs:
#           - name: secret-tls
#             namespace: default

#       allowedRoutes:
#         namespaces:
#           from: Same
