POSTGRES_PASSWORD: ENC[AES256_GCM,data:goMY5aeNGUMwdOSvAO/j3w==,iv:PBUBHnfrny0SeAciEJfG81EfNI3dopPumWPovIXWAXw=,tag:p1yOs0u8dJbEVssMJ9NW1g==,type:str]
sops:
  lastmodified: "2025-10-14T14:48:45Z"
  mac: ENC[AES256_GCM,data:mzDjrv2SAaRsW8tIHpCcyZRt23Tw+p8yE7/7+jn3mmPIK4zwuJspXDzTwDMDMNuoq3e9sCRQt6EnANIPBQuBXyXQnO2XZakgh5RZA05vPDt6sSZdnSLhCwsnHIkaQ+L9MQ686G9sS+B9BeWlIFy7zXrWcyULCHOK2nZRU2VHiZc=,iv:+4FtYTLtwZEopDe8tciejE5ZB8AUtfxsPq2oes1Hoe4=,tag:xVLk7MI2DvjpTmAakBMg/g==,type:str]
  pgp:
    - created_at: "2025-10-14T14:48:45Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DibhzSPCfsQESAQdAVamB4ZxSO550fCSJrSDR9pS5sZ+sSMCbpwA+sqv7CB4w
        D9704e6YHK4VMhCQ1OMijO2HQK+qOK7iwaHYaBoE/nE+E9xMXaED1QjIoO+jvCF5
        1GgBCQIQsuAYNh6DQ7L0cbHeM5dj5z8jtdR7xkhNqEzUAPzBfmeMGmBWPFzpNoui
        Fx1Zvy1gXGuJ751n75EAtgTyXJVM5wKRGsqTQ+dSuwDB09ibGu5D46GlyGFBoV3T
        Dp4o+aVEQoeO2g==
        =dFux
        -----END PGP MESSAGE-----
      fp: 3205D67C84CD0480A16BBC7CF83561A568B69B43
  unencrypted_suffix: _unencrypted
  version: 3.11.0
