apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vex-api.fullname" . }}
  labels:
    {{- include "vex-api.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}
  
  POSTGRES_DATABASE: {{ .Values.postgres.database }}
  POSTGRES_USERNAME: {{ .Values.postgres.username }}
  
  ACCOUNT_MAX_ALIASES: '3'
  ACCOUNT_ALIAS_EXPIRY_SHORT: 1d
  ACCOUNT_ALIAS_EXPIRY_LONG: 1mo
