apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    {{- include "vex-api.labels" . | nindent 4 }}
data:
  auth.database: vex
  auth.username: vex
  auth.enablePostgresUser: 'false'
