apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "vex-db.fullname" . }}-migration-config"
  labels:
    {{- include "vex-db.labels" . | nindent 4 }}
data:
  POSTGRES_HOSTNAME: {{ .Values.migration.postgres.hostname }}
  POSTGRES_PORT: {{ .Values.migration.postgres.port | quote }}
  POSTGRES_DATABASE: {{ .Values.migration.postgres.database }}
  POSTGRES_USERNAME: {{ .Values.migration.postgres.username }}
  