apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.auth.existingSecret }}
  labels:
    {{- include "vex-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: "ref+sops://k8s/secrets.yaml#/POSTGRES_PASSWORD"
  postgres-password: "ref+sops://k8s/secrets.yaml#/POSTGRES_ADMIN_PASSWORD"
  replication-password: "ref+sops://k8s/secrets.yaml#/POSTGRES_REPLICATION_PASSWORD"
