apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.postgres.secretName }}
  labels:
    {{- include "vex-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: "ref+sops://k8s/secrets.yaml#/POSTGRES_PASSWORD"
