replicaCount: 1

image:
  repository: ''
  pullPolicy: IfNotPresent
  tag: ''

nameOverride: ''
fullnameOverride: ''

podAnnotations: {}
podLabels: {}

service:
  # type: ClusterIP
  port: 8080

gateway:
  name: traefik-gateway
  namespace: traefik
