replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8080

postgres:
  primary:
    existingConfigmap: 'postgres-config'
    existingSecret: 'postgres-secrets'
