replicaCount: 1

image:
  repository: ''
  pullPolicy: IfNotPresent
  tag: ''

nameOverride: ''
fullnameOverride: ''

podAnnotations: {}
podLabels: {}

service:
  port: 8080

gateway:
  name: traefik-gateway
  namespace: traefik
  sectionName: api

tls:
  namespace: traefik

postgres:
  database: vex
  username: vex

account:
  alias:
    max: 3
    expiry:
      short: 1d
      long: 1mo
