replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  # type: ClusterIP
  port: 8080

postgres:
  auth.existingSecret: 'postgres-secrets'
  primary.existingConfigmap: 'postgres-config'

gateway:
  name: traefik-gateway
  namespace: traefik
